package com.bureng.robocoinx.utils;

public class StaticValues {

    public static final String OP = "free_play";
    public static final String RESET_PASSWORD = "forgot_password";
    public static final String CHANGE_PASSWORD = "change_password";
    public static final String WITHDRAW = "withdraw";
    public static final String WITHDRAW_TYPE_SLOW = "slow";
    public static final String AUTH_COOKIES = "auth_cookies";
    public static final String ERROR_GENERAL = "General Error";
    public static final String NOTIFICATION_ROLL = "notification_roll";
    public static final String OP_SIGNUP = "signup_new";
    public static final String SIGNUP_REQ = "signup_req";
    public static final String STATE_LOGIN = "login";
    public static final String STATE_SIGNUP = "signup";
    public static final String LAST_DATE = "last_play_date";
    public static final String FP100 = "free_points_100";
    public static final String FP50 = "free_points_50";
    public static final String FP25 = "free_points_25";
    public static final String FP10 = "free_points_10";
    public static final String FP1 = "free_points_1";
    public static final String FB_50 = "fp_bonus_50";
    public static final String FB_100 = "fp_bonus_100";
    public static final String FB_500 = "fp_bonus_500";
    public static final String REGEX_SCRIPT_1 = "https://static1.freebitco.in/min/combined";
    public static final String REGEX_SCRIPT_2 = "var tcGiQefA =";
    public static final String REGEX_SCRIPT_3 = "https://static1.freebitco.in/min/main";
    public static final String REGEX_SCRIPT_4 = "https://static1.freebitco.in/min/compressed_bottom";
    public static final String REGEX_SCRIPT_5 = "https://ajax.cloudflare.com/cdn-cgi/scripts";
    public static final String CACHE = "CACHE";
    public static final String FINGERPRINT = "FINGERPRINT";
    public static final String STATE_BEFORE_SIGNUP = "Before Sign Up";
    public static final String DEPOSIT_ADDRESS = "Deposit Address";
    public static final String DEPOSIT_AMOUNT = "Deposit Amount";
    public static String URL_KEY_B = "aHR0cHM6Ly9mcmVlYml0Y28uaW4v";
    public static String URL_KEY_H = "aHR0cHM6Ly9mcmVlYml0Y28uaW4vP29wPWhvbWU=";
    public static String URL_KEY_S = "aHR0cHM6Ly9mcmVlYml0Y28uaW4vP29wPXNpZ251cF9wYWdl";
    public static String URL_KEY_O = "ZnJlZWJpdGNvLmlu";
    public static String URL_KEY_A = "aHR0cHM6Ly9mcmVlYml0Y28uaW4=";
    public static String URL_KEY_C = "aHR0cHM6Ly9mcmVlYml0Y28uaW4vY2dpLWJpbi9mcF9jaGVjay5wbD9zPQ==";
    public static String URL_KEY_LT = "aHR0cHM6Ly9mcmVlYml0Y28uaW4vP29wPXRvZ2dsZV9sb3R0ZXJ5JnZhbHVlPTE=";
    public static String URL_KEY_IN = "aHR0cHM6Ly9mcmVlYml0Y28uaW4vP29wPXRvZ2dsZV9pbnRlcmVzdCZ2YWx1ZT0w";
    public static String USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36";
    public static final String CSRF_TOKEN = "csrf_token";
    public static final String USER_CACHE = "user_cache";
    public static final String PROFILE_VIEW = "profile_view";
    public static final String START_SERVICE = "start_service";
    public static final String STOP_SERVICE = "stop_service";
    public static final String CREATE_SERVICE = "create_service";
    public static final String BOOT_COMPLETED = "android.intent.action.BOOT_COMPLETED";
    public static final String CURRENT_BALANCE = "current_balance";
    public static final String EMAIL = "email";
    public static int TIMEOUT = 50000;
    public static final int POINT_1600 = 1600;
    public static final int POINT_1200 = 1200;
    public static final int POINT_800 = 800;
    public static final int POINT_600 = 600;
    public static final int POINT_400 = 400;
    public static final int POINT_320 = 320;
    public static final int POINT_300 = 300;
    public static final int POINT_160 = 160;
    public static final int POINT_120 = 120;
    public static final int POINT_12 = 12;
    public static final int MY_IGNORE_OPTIMIZATION_REQUEST = 1613;
    public static final String BASE_URL = "https://freebitco.in/";
    public static final String KEY_SECRET = "#7H3g0Df4Th312##";
    public static final String FIREBASE_EMAIL = "harrysusanto13@gmail.com";
    public static final String FIREBASE_PASS = "robocoinX999";
}
